### ISSUE TITLE
Add `rand` unitary initialization of `Chain` 

### ISSUE THREAD

**Issue by jofrevalles** [bsc-quantic/Qrochet.jl#12]
### Summary
In [`Tenet v0.3.0`](https://github.com/bsc-quantic/Tenet.jl/blob/v0.3.0/src/Quantum/MP.jl#L134) we added the possibility to initialize an `MPS` or `MPO` using Gram-Schmidt in order to create a state that is directly unitary. This feature could be added now into Qrochet.

**Comment by mofeing** [comment]
We could also implement the "eye" initialization.
