### ISSUE TITLE
Add truncate function for tensors in a `Chain`

### ISSUE THREAD

**Issue by jofrevalles** [bsc-quantic/Qrochet.jl#13]
### Summary
Add a `truncate` function that truncates a tensor in a `Chain`. This function should look into the state, check for singular values, and truncate accordingly.

**Comment by mofeing** [comment]
Just a note: This `truncate` function implements local truncation of a virtual index. Whether that local truncation is globally optimal depends on the canonization.

**Comment by jofrevalles** [comment]
Closing this as it was implemented in PR #16
